name: Unit Testing CI for Testing Module

on: pull_request

defaults:
  run:
    working-directory: ./Modulo 5

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Automated Tests
        run: npm run test:e2e:ci
